# Generated by Django 4.2.4 on 2023-08-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakrand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('band_material', models.CharField(max_length=20)),
                ('interface', models.CharField(choices=[('digital', 'Digital'), ('analog', 'Analog')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
