# Generated by Django 4.2.4 on 2023-08-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_breakrand_watch_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='interface',
            field=models.CharField(choices=[('digital', 'Digital'), ('analog', 'Analog')], max_length=20),
        ),
    ]
